language: java
jdk:
  - oraclejdk8
rvm:
 - 2.2
env:
- secure: "B/NbDu83CxM3CzGFiaMhx0T4G2MPH3C5/zplXgglJE1y88HLXmUKlR1Qj2IEm/of157TT7m03LwzZ89uqlvBPe0gOzmqem+0haAws1YFaVf+8xaHRvqECqmQgsTyhurqhJ4hFwsw3aSutS3wqiuVwPNNRndGQr9bP8LQDqb5I1W2N0UBqrAY5+r6cjU+KzOPDUbl4xgX+ATNVHW8VxU65dEpalZN2DJSkmg3OCI/QBpE1RY6SF2wAgCaLKcpU++OlEDF0dGreCV0gqQyZ1YqQHUxF8iOJgCJQePJoVbjaNHfqOdpVghLZsiC79EUH6gR+NMaKXrkYlP/6dv4Obu/enJbXUx0Fei+UIksqJ2wCv0+l71OT/EqGLkMjXa6xuyKutBQHmjNG7xXXCxgmQR0M6zknBRivsXvk8YWD+n+q0S7hPwawik7qlJGYx3G52VFP/GwjgXEecal2vvtH2c1iZXluy3yf7dCTIBbltuOIKNxlKgH9BUKBMS7RvvVYGKDa49anC0uTWY6IsPFWE5WHXR31Z7XLMD7AYBch5OPGWHZ2qlZBO+LPWZnx6Ok8VdNmMAeUATGBraYEwjfZDEiYcch6hcMrHGEkra5mk9WCb7wh1GIkBxzxuvyofSmV0fs9WaBf9WfQ3+sT1EZbJ+0EJvdeL+ZAjUTuyYSD5VPNJQ="
git:
  submodules: false
before_install:
- git config --global user.email "$GIT_EMAIL"
- git config --global user.name "$GIT_NAME"
- ./scripts/install-calico.sh
- git submodule update --init --recursive
- git submodule foreach git pull origin master
- git submodule foreach git checkout master
script:
- ./scripts/prepare.sh
- ./Calico/release/bin/calico build
- ./scripts/publish.sh
